service: shop-backend-serverless

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: eu-central-1

  httpApi:
    cors: true

  environment:
    PRODUCTS_TABLE:
      Ref: productsTable
    STOCK_TABLE:
      Ref: stockTable

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:Scan"
            - "dynamodb:GetItem"
          Resource:
            - Fn::GetAtt: [productsTable, Arn]
            - Fn::GetAtt: [stockTable, Arn]

functions:
  getProductsList:
    handler: handler.getProductsList
    events:
      - httpApi:
          path: /products
          method: get
  getProductsById:
    handler: handler.getProductsById
    events:
      - httpApi:
          path: /products/{productId}
          method: get
  createProduct:
    handler: handler.createProduct
    events:
      - httpApi:
          path: /products
          method: post

resources:
  Resources:
    productsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: products
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    stockTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: stock
        AttributeDefinitions:
          - AttributeName: product_id
            AttributeType: S
        KeySchema:
          - AttributeName: product_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
