service: import-service

frameworkVersion: "3"

custom:
  bucketName: shop-backend-serverless-import
  bucketArn: arn:aws:s3:::${self:custom.bucketName}
  bucketPrefix: uploaded
  authorizerArn:
    Fn::ImportValue: BasicAuthorizerLambdaFunctionArn


provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: eu-central-1
  httpApi:
    cors: true
    authorizers:
      basicAuthorizer:
        type: request
        functionArn: ${self:custom.authorizerArn}

  iam:
    role:
      statements:
        - Effect: Allow
          Action: s3:PutObject
          Resource: ${self:custom.bucketArn}
        - Effect: Allow
          Action: sqs:*
          Resource:
            Fn::ImportValue: CatalogItemsQueueArn
  environment:
    BUCKET_NAME: ${self:custom.bucketName}
    UPLOAD_DIR: ${self:custom.bucketPrefix}
    QUEUE_URL:
      Fn::ImportValue: CatalogItemsQueueUrl

functions:
  importProductsFile:
    handler: handler.importProductsFile
    events:
      - httpApi:
          path: /import
          method: get
          authorizer:
            name: basicAuthorizer

  importFileParser:
    handler: handler.importFileParser
    events:
      - s3:
          bucket: ${self:custom.bucketName}
          existing: true
          event: s3:ObjectCreated:*
          rules:
            - prefix: "${self:custom.bucketPrefix}/"
